server:
  http_listen_port: {%HTTPPORT%}
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{%LOKI_LISTEN_ADDRESS%}:{%LOKI_LISTEN_PORT%}/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      labels:
        job: systemd-journal
        level:
      max_age: 24h
      path: /var/log/journal

    relabel_configs:
      - source_labels:
          - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
          - __journal__systemd_user_unit
        target_label: systemd_user_unit
      - source_labels:
          - __journal__hostname
        target_label: nodename
      - source_labels:
          - __journal_syslog_identifier
        target_label: syslog_identifier
      - source_labels:
          - __journal__transport
        target_label: transport

    pipeline_stages:
      # 过滤系统服务日志
      - drop:
          source: syslog_identifier
          expression: ".*{%EXCLUDE_SERVICES%}.*"
      - match:
          selector: '{systemd_unit="jsy-archiver.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%JSY_ARCHIVER_LOG_REGEX%}"
            - labels:
                level:
                archiver_job:
                conclusion:
      - match:
          selector: '{systemd_unit="wind-importer.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%WIND_IMPORTER_LOG_REGEX%}"
            - labels:
                level:
                importer_job:
                conclusion:
      - match:
          selector: '{systemd_unit="jsy-importer.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%JSY_IMPORTER_LOG_REGEX%}"
            - labels:
                level:
                importer_job:
                conclusion: